### PR TITLE
timeout option in redisConnectWithOptions should be on the connect op…

### PR DESCRIPTION
**Pull request by valentinogeron**
…eration only

in order to set timeout for commands we should use redisSetTimeout

### CODE REVIEW

**Comment by valentinogeron** [comment]
when a timeout is specified as an option for `redisConnectWithOptions` (or its equivalents e.g `redisConnectWithTimeout`), it configures the created `redisContext` to use this timeout for command as well.
The current implementation is not backward compatible and may break applications.

My suggestion is that if the application would choose to use a timeout for commands as well, it will have to call `redisSetTimeout` explicitly.

@michael-grunder what do you think?

**Comment by michael-grunder** [comment]
I tend to agree they should be distinct (Related issue: #722).

We are able to break things (since we've not yet released v1.0.0) but once we do we'll be stuck with it until 2.0.0.

I lean toward merging the PR but I suppose we could to a third route and add a distinct `command_timeout` to `redisContextOptions` so the user could specify both.

@yossigo Any preference?

**Comment by yossigo** [comment]
@michael-grunder I agree, I think this PR is a bugfix because there's really no justification to break compatibility. An explicit command timeout seems like a good idea regardless of the fix.

**Comment by yossigo** [comment]
@michael-grunder just to confirm with you, I think this fix should be part of 1.0.0 and the command_timeout improvement is nice to have but not must. What do you think?

**Comment by michael-grunder** [comment]
Yes, I'll make sure to merge this before we release v1.0.0.

I want to implement proper handling for `>` PUSH messages as well but then I think we can call v1.0.0 feature complete.

**Comment by michael-grunder** [comment]
Merged, thanks @valentinogeron!

**Pull request merged**
