### PR TITLE
Windows support pull request

### PR DESCRIPTION
**Pull request by koenvandesande**
Based on https://github.com/antirez/hiredis/pull/48 , this is my version of it which cleans up some issues and avoids the requirements for all users of the library to include config.h.

### CODE REVIEW

**Comment by aleks-f** [comment]
I agree about the need for Windows support. For CI, there is [Visual Studio Online](http://www.visualstudio.com/en-us/products/what-is-visual-studio-online-vs). Is there any possibility to get this pull merged?

**Comment by francesco-loreti** [comment]
Any news? Because now when I try to install Rails 5 Beta1 hiredis gem version 0.5.2  is required and I can't do that because it's not compatible with windows so what can I do? Thanks

**Comment by badboy** [comment]
Wait for the update on hiredis-rb ;)

**Comment by BeeZerk** [comment]
+1 waiting

**Comment by koenvandesande** [comment]
You should use the hiredis that is part of the Microsoft Open-Source Redis version: https://github.com/MSOpenTech/redis
That one fully works on Windows. The version in this pull request doesn't merge (at all) with the latest hiredis.

**Pull request closed without merging**
