### PR TITLE
Add travis support for s390x

### PR DESCRIPTION
**Pull request by cnnaik**
Add travis support for s390x for Hiredis.

### CODE REVIEW

**Comment by michael-grunder** [comment]
Thanks for the PR!

I'm not familiar with the s390x architecture but it looks like the tests pass.  

Is the arch/kernel different enough that you would expect us to encounter breaking changes with respect to it?  I'm trying to weigh whether or not the 20 added minutes to CI is likely to ever find problems.

**Comment by cnnaik** [comment]
> Thanks for the PR!
> 
> I'm not familiar with the s390x architecture but it looks like the tests pass.
> 
> Is the arch/kernel different enough that you would expect us to encounter breaking changes with respect to it? I'm trying to weigh whether or not the 20 added minutes to CI is likely to ever find problems.

@michael-grunder s390x is a 64 bit, big endian architecture.

**Comment by cnnaik** [comment]
@michael-grunder Please let us know if there is any update on this.

**Comment by cnnaik** [comment]
@michael-grunder Is there any further discussion on this PR, please let us know if any more information is needed from our side.

**Comment by cnnaik** [comment]
@michael-grunder Is there any further progress on this PR, please let us know if any more information is needed from our side.

**Comment by michael-grunder** [comment]
I actually need to migrate all of our tests to GitHub actions as travis-ci.org is now deprecated.

It looks like Actions does support s390x so we could add it after I create the initial `.github/workflows/build.yml`

**Comment by cnnaik** [comment]
@michael-grunder Do we have any plans to migrate the repository to travis-ci.com? As per the Travis [blog](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), Travis fully supports the OSS teams and allocates them more credits after they apply for the same.

**Comment by michael-grunder** [comment]
I believe that would need to be done by the owners of the Redis organization (Redis Labs), as I only have access to this repo.

That said, it looks like Redis itself has migrated to GitHub actions so doing the same for hiredis seems like the way to go.  The workflows are pretty similar though, and s390x is supported so I will make sure to get this functionality included with the migration.

**Comment by cnnaik** [comment]
Thanks @michael-grunder for the update.

**Pull request closed without merging**
