### PR TITLE
fix some compile problem in cygwin and msys, add ci inwindows

### PR DESCRIPTION
**Pull request by owt5008137**
1. add ci in windows(cygwin)
2. fix macro problem in test.c when using msys
3. fix typedef problem when using latest cygwin

PS: I just write windows ci configure file ([appveyor.yml](https://ci.appveyor.com/project/owt5008137/hiredis/) ) and test it in my account.It's better to add status image to README.md by @antirez , just like travis ci. So I did nothing to README.md

### CODE REVIEW

**Comment by owt5008137** [comment]
issue #355 is just a part of this request

**Comment by owt5008137** [comment]
@xiaotaoz I have already create this pull request. but it's decide to @badboy when to merge it or not.
PS: hiredis v0.13.3 fix  the lost of disconnect callback by another way.

**Comment by owt5008137** [comment]
@xiaotaoz you are right I will remove it soon

**Comment by badboy** [comment]
Pulling it in in #414

**Pull request closed without merging**
