### PR TITLE
remove unnecessory code

### PR DESCRIPTION
**Pull request by charsyam**
remove some  unnecessory code. It is not used any other parts

### CODE REVIEW

**Comment by badboy** [comment]
I'm in the process of pulling in the updated sds. Does the problem still exist there? Can you sent the patch upstream as well?

**Comment by charsyam** [comment]
@badboy I found it from current master :)

**Comment by badboy** [comment]
@charsyam Mind rebasing against master again?

**Comment by charsyam** [comment]
@badboy I rebased it :) Please review it :)

**Comment by badboy** [comment]
@not-a-robot r+

**Pull request merged**
