### PR TITLE
Update hiredis sds with improvements found in redis

### PR DESCRIPTION
**Pull request by bjosv**
Update hiredis sds with improvements found in redis for convergence,
like the overflow mentioned in https://github.com/redis/redis/issues/9706

Handpicked from:
https://github.com/redis/redis/pull/4568
https://github.com/redis/redis/pull/9584
https://github.com/redis/redis/pull/8522

### CODE REVIEW

**Comment by bjosv** [comment]
Ouch, it looks like CentOS8 has gone [EOL](https://www.centos.org/centos-linux-eol/) and that we need to do some updates for CI.

**Comment by michael-grunder** [comment]
I actually ran into the CentOS issue yesterday [and even complained about it on Twitter](https://twitter.com/grumi78/status/1488338054100099074) :smile:

I believe there is a short-term solution to this.  I'll get that up now.

**Comment by michael-grunder** [comment]
Thanks for porting these over.

I wonder if we can avoid the `assert`s on overflow though.  Simply return `NULL` instead so the error is just treated like an `OOM` for clients of the library.

**Comment by bjosv** [comment]
> I wonder if we can avoid the `assert`s on overflow though. Simply return `NULL` instead so the error is just treated like an `OOM` for clients of the library.

Yes, you are right, much better. This follows how its handled in other places

**Comment by bjosv** [comment]
Sorry, touchpad gone wild.. updated the PR with the change.

**Comment by michael-grunder** [comment]
Merged, thanks!

**Pull request merged**
