### PR TITLE
Added package configs and fixed hiredis_ssl on Windows

### PR DESCRIPTION
**Pull request by heronr**
This change mainly accomplishes 2 things:

1. A CMake build now generates package config files for both hiredis and hiredis_ssl. This enables other CMake projects to use find_package() calls to more easily incorporate hiredis into their project.

1. hiredis_ssl now builds on Windows using the CMake project

I was able to successfully build on both Windows and Linux using these changes.

### CODE REVIEW

**Comment by heronr** [comment]
This should hopefully not be a controversial change. Nevertheless, is it preferred that I actually split this into 2 PRs since it combines 2 unrelated changes?

**Comment by heronr** [comment]
@michael-grunder Does this seem reasonable? Should I create an issue to correspond with this change?

**Comment by michael-grunder** [comment]
It does seem reasonable to me but I am not overly familiar with CMake so I would defer to @mnunberg in that respect and @yossigo for the SSL changes (since he wrote those).

**Comment by yossigo** [comment]
Hi @heronr, not a CMake expert but it looks perfectly reasonable to me. Same for the SSL locking changes, thanks!

**Comment by michael-grunder** [comment]
Thanks for another set of eyes @yossigo!

@heronr I'll fix the conflicts since I broke it with another commit and get this merged before we release 1.0.0.

**Comment by yossigo** [comment]
@heronr Looking at another CMake related issue now and I noticed this:

```
SET_TARGET_PROPERTIES(hiredis
    PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS TRUE
    VERSION "${HIREDIS_SONAME}")
```

Doesn't this make the explicit def files redundant?

**Comment by michael-grunder** [comment]
I added the `WINDOWS_EXPORT_ALL_SYMBOLS` and removed the `.def` file in cc9d03297177eb8504c7353db673b9dc6f64ea07.

My motivation was getting our unit tests working in Windows, including the various different ways one might do that (e.g. build with MSVC, MinGW, or Cygwin) as they needed slightly different exports.

I'm happy to fix the conflicts so we can get this merged.

**Comment by yossigo** [comment]
@michael-grunder Oh okay, haven't really looked around but bumped into this while pushing #780. Thanks!

**Comment by michael-grunder** [comment]
Hi @heronr I fixed the merge conflicts on your PR [in this branch on my fork](https://github.com/michael-grunder/hiredis/tree/cmake-config-win-ssl)

The only substantive change I made was using to `WINDOWS_EXPORT_ALL_SYMBOLS` instead of `.def` files.  That said, I'm quite unfamiliar with the Windows ecosystem so please let me know if there is a reason we shouldn't do that.

If the changes look good to you I'm happy to merge it into master or if you prefer you could merge my modifications into your PR branch and I'll merge this PR.

Thanks for your contribution!

Cheers,
Mike

**Comment by heronr** [comment]
@michael-grunder , the changes you made look good to me. You can go ahead and merge those changes in. Thank you!

**Comment by michael-grunder** [comment]
Closing in favor of #783

**Pull request closed without merging**
