### PR TITLE
Add timeout support to libhv adapter.

### PR DESCRIPTION
**Pull request by michael-grunder**
Add timeout support to our libhv adapter.

See: #904

### CODE REVIEW

**Comment by michael-grunder** [comment]
cc @ithewei This is my attempt to add timeout support to your adapter.  I'm unfamiliar with the library so please let me know if my usage is correct.

**Comment by ithewei** [comment]
> 

You are right, and you can use `htimer_reset` to update timeout multiple times.

**Comment by ithewei** [comment]
> cc @ithewei This is my attempt to add timeout support to your adapter. I'm unfamiliar with the library so please let me know if my usage is correct.
> 
> Edit: I think this logic isn't ideal if users update the timeouts multiple times (as it will add a bunch of timers). Is there a mechanism in `libhv` to find an already existing timer?

You are right, and you can use htimer_reset to update timeout multiple times.

**Comment by michael-grunder** [comment]
@ithewei If you don't mind taking a look at the new timeout logic that would be great.  In reading the `libhv` source code I saw that there are several "built-in" timers in the `hio_t` structure, but it was unclear to me whether I could safely use any of them for this purpose.

@bjosv Let me know if anything jumps out at you.  It should now be possible/efficient to update timeouts arbitrarily when using `libhv`.

**Review by bjosv — APPROVED** [review]
Nice!
Maybe example users would get helped by a comment in `debugCallback()` that we expect a NULL reply since DEBUG SLEEP should timeout..
..but it LGTM as is.

**Pull request merged**
