### PR TITLE
Don't pass a negative value to __redisAsyncCommand if redisFormatSdsCommandArgv fails

### PR DESCRIPTION
**Pull request by deweerdt**

### CODE REVIEW

**Comment by michael-grunder** [comment]
Looks good to me, nice find!

**Comment by deweerdt** [comment]
I'm confused by https://github.com/redis/hiredis/pull/524#issuecomment-315538991 it does look like the code landed on master?

**Comment by badboy** [comment]
That's what you get for mixing mutliple bots into one repo. The change landed, the @not-a-robot user is legacy.

**Comment by deweerdt** [comment]
:+1: thanks for the explanation.

**Pull request merged**
