### PR TITLE
New SSL API to replace redisSecureConnection().

### PR DESCRIPTION
**Pull request by yossigo**

### CODE REVIEW

**Comment by carlosabalde** [comment]
Just FYI ,I integrated the new API in a project and it looks great. I found a [minor issue](https://github.com/redis/hiredis/commit/8e0264cfd6889b73c241b60736fe96ba1322ee6e#commitcomment-39412934), but unrelated with this PR. Thanks!

**Comment by yossigo** [comment]
@michael-grunder Can you have a look as well please? It should be fairly trivial but I'd be happy for another set of eyes on this...

I guess over time we may want to improve OpenSSL defaults for better security, OpenSSL compatibility and sanity (or, more realistically, just any two of those).

**Comment by michael-grunder** [comment]
@yossigo Happy to take a look.  I'll run the new API through the allocator stress test I created for #800 as well.

@carlosabalde Your issue should be fixed in f5d258504333d5598428853b7293e26814f65acf.  Let me know if it's still causing issues.

**Comment by michael-grunder** [comment]
Merged, thank you @yossigo!

**Pull request merged**
